# all_mod = {
#     "accChest": [1, 2, 3],
#     "EKG": [4, 5],
#     "accLa": [6, 7, 8],
#     "gyroLa": [9, 10, 11],
#     "magLa": [12, 13, 14],
#     "accRa": [15, 16, 17],
#     "gyroRa": [18, 19, 20],
#     "magRa": [21, 22, 23]
#  }



# all_mod = {
#     "all": [
#         1,
#         2,
#         3,
#         6,
#         7,
#         8,
#         15,
#         16,
#         17,
#         9,
#         10,
#         11,
#         18,
#         19,
#         20,
#         12,
#         13,
#         14,
#         21,
#         22,
#         23,
#     ],
#     "acc": [1, 2, 3, 6, 7, 8, 15, 16, 17],
#     "gyro": [9, 10, 11, 18, 19, 20],
#     "mag": [12, 13, 14, 21, 22, 23],
# }